spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    streams:
      application-id: test-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
